%% Methodology Block Diagram
% Observer-based reduced-order electromagnetic stress regulation framework

clear; clc; close all;

figure('Color','white');
set(gcf,'Position',[200 100 900 1100]);

axis off;

%% Parameters

boxWidth = 0.28;
boxHeight = 0.055;

x = 0.36;

y = [
    0.88
    0.77
    0.66
    0.55
    0.43
    0.30
    0.16
];

labels = {
    sprintf('Distributed Multiphysics System\n(Maxwell Stress Tensor Field)')
    sprintf('Synthetic Snapshot Generation\n(Stress Fields, Disturbances, Thermal Drift)')
    sprintf('Proper Orthogonal Decomposition (POD)\nModal Reduction')
    sprintf('Reduced-Order State-Space Model')
    sprintf('Observer-Based Control Architecture')
    sprintf('LQG Baseline\n(LQR + Kalman Estimator)')
    sprintf('Robust Sliding Mode Control Extension')
};

%% Draw main vertical chain

for i = 1:length(y)

    annotation('textbox',...
        [x y(i) boxWidth boxHeight],...
        'String',labels{i},...
        'Interpreter','latex',...
        'HorizontalAlignment','center',...
        'VerticalAlignment','middle',...
        'FontSize',9,...
        'EdgeColor','black',...
        'BackgroundColor',[1 1 1],...
        'FitBoxToText','off');

end


%% Arrows

for i = 1:length(y)-1

    annotation('arrow',[0.50 0.50],[y(i) y(i+1)+boxHeight]);

end

%% Split LQG / SMC architecture

% Left branch: State estimation
annotation('textbox',...
    [0.16 0.39 0.16 0.055],...
    'String',sprintf('State Estimation\n(Kalman Observer)'),...
    'Interpreter','latex',...
    'HorizontalAlignment','center',...
    'VerticalAlignment','middle',...
    'FontSize',9,...
    'EdgeColor','black',...
    'FitBoxToText','off');

annotation('arrow',...
    [0.50 0.24],...
    [0.55 0.445]);


% Right branch: Feedback
annotation('textbox',...
    [0.68 0.39 0.16 0.055],...
    'String',sprintf('Optimal Feedback\n(LQR Control)'),...
    'Interpreter','latex',...
    'HorizontalAlignment','center',...
    'VerticalAlignment','middle',...
    'FontSize',9,...
    'EdgeColor','black',...
    'FitBoxToText','off');

annotation('arrow',...
    [0.50 0.76],...
    [0.55 0.445]);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%% Final Output

annotation('textbox',...
    [0.28 0.05 0.44 0.06],...
    'String',sprintf('Closed-Loop Electromagnetic Stress Regulation\n\\textbf{Performance Evaluation}'),...
    'HorizontalAlignment','center',...
    'Interpreter','latex',...
    'VerticalAlignment','middle',...
    'FontSize',9);


annotation('arrow',[0.50 0.50],[0.16 0.11]);
